const menu = document.querySelector('.menu-toggle');
const nav = document.querySelector('nav');

if (menu && nav) {
  menu.addEventListener('click', () => {
    const open = nav.classList.toggle('active');
    menu.setAttribute('aria-expanded', String(open));
  });

  document.querySelectorAll('nav a').forEach(link => {
    link.addEventListener('click', () => {
      nav.classList.remove('active');
      menu.setAttribute('aria-expanded', 'false');
    });
  });
}

const year = document.getElementById('year');
if (year) year.textContent = new Date().getFullYear();

function playDemo(btn) {
  btn.textContent = '✓';
  setTimeout(() => btn.textContent = '▶', 900);
}

const T = {
  en:{navHome:'Home',navAbout:'About',navMusic:'Music',navVideos:'Videos',navServices:'Services',navContact:'Contact',eyebrow:'DJ • MUSIC • ENTERTAINMENT',tagline:'MUSIC HITS DIFFERENT.',heroText:'Turn up the energy. Feel the beat. Enter Sniper Mode.',explore:'Explore Music',sniper:'SNIPER MODE ON',aboutTitle:'Built for the Beat.',aboutText:'DJ Sniper is a music and entertainment brand focused on high-energy DJ experiences, original music, collaborations and digital content.',card1:'Music',card1t:'DJ sets, mixes, rap, kuthu and original sounds.',card2:'Energy',card2t:'Powerful sound, attitude and unforgettable moments.',card3:'Collabs',card3t:'Artists, creators, events and brand collaborations.',musicTitle:'Music Hits Different.',videoTitle:'Videos & Content',ytLater:'YouTube channel coming soon.',servicesTitle:"Let's Create Something Loud.",service1:'DJ Booking',service1t:'Events, parties and special occasions.',service2:'Music Projects',service2t:'Rap, DJ, kuthu and creative music projects.',service3:'Events & Collabs',service3t:'Artists, event teams, creators and brands.',contactTitle:'Book. Collaborate. Connect.',youtubeLater:'YouTube: coming soon'},
  mr:{navHome:'मुख्यपृष्ठ',navAbout:'आमच्याबद्दल',navMusic:'संगीत',navVideos:'व्हिडिओ',navServices:'सेवा',navContact:'संपर्क',eyebrow:'DJ • संगीत • मनोरंजन',tagline:'संगीत वेगळंच वाटतं.',heroText:'ऊर्जा वाढवा. बीट अनुभवा. Sniper Mode मध्ये या.',explore:'संगीत ऐका',sniper:'SNIPER MODE ON',aboutTitle:'बीटसाठी तयार.',aboutText:'DJ Sniper हा उच्च-ऊर्जा DJ अनुभव, ओरिजिनल संगीत, collaborations आणि digital content वर आधारित music & entertainment brand आहे.',card1:'संगीत',card1t:'DJ sets, mixes, rap, kuthu आणि original sounds.',card2:'ऊर्जा',card2t:'Powerful sound, attitude आणि unforgettable moments.',card3:'Collabs',card3t:'Artists, creators, events आणि brands सोबत collaboration.',musicTitle:'संगीत वेगळंच वाटतं.',videoTitle:'व्हिडिओ आणि कंटेंट',ytLater:'YouTube channel लवकरच.',servicesTitle:'काहीतरी दमदार तयार करूया.',service1:'DJ Booking',service1t:'Events, parties आणि special occasions.',service2:'Music Projects',service2t:'Rap, DJ, kuthu आणि creative music projects.',service3:'Events & Collabs',service3t:'Artists, event teams, creators आणि brands.',contactTitle:'Booking • Collaboration • संपर्क',youtubeLater:'YouTube: लवकरच'},
  hi:{navHome:'होम',navAbout:'हमारे बारे में',navMusic:'संगीत',navVideos:'वीडियो',navServices:'सेवाएं',navContact:'संपर्क',eyebrow:'DJ • संगीत • मनोरंजन',tagline:'संगीत का अंदाज़ अलग है।',heroText:'एनर्जी बढ़ाइए। बीट महसूस कीजिए। Sniper Mode में आइए.',explore:'संगीत सुनें',sniper:'SNIPER MODE ON',aboutTitle:'बीट के लिए तैयार।',aboutText:'DJ Sniper एक music और entertainment brand है जो high-energy DJ experiences, original music, collaborations और digital content पर केंद्रित है.',card1:'संगीत',card1t:'DJ sets, mixes, rap, kuthu और original sounds.',card2:'एनर्जी',card2t:'Powerful sound, attitude और unforgettable moments.',card3:'Collabs',card3t:'Artists, creators, events और brands के साथ collaboration.',musicTitle:'संगीत का अंदाज़ अलग है।',videoTitle:'वीडियो और कंटेंट',ytLater:'YouTube channel जल्द आ रहा है.',servicesTitle:'कुछ दमदार बनाते हैं।',service1:'DJ Booking',service1t:'Events, parties और special occasions.',service2:'Music Projects',service2t:'Rap, DJ, kuthu और creative music projects.',service3:'Events & Collabs',service3t:'Artists, event teams, creators और brands.',contactTitle:'Booking • Collaboration • संपर्क',youtubeLater:'YouTube: जल्द ही'},
  ta:{navHome:'முகப்பு',navAbout:'எங்களைப் பற்றி',navMusic:'இசை',navVideos:'வீடியோக்கள்',navServices:'சேவைகள்',navContact:'தொடர்பு',eyebrow:'DJ • இசை • பொழுதுபோக்கு',tagline:'இசை வித்தியாசமாக இருக்கும்.',heroText:'எனர்ஜியை உயர்த்துங்கள். பீட்டை உணருங்கள். Sniper Mode-க்கு வாருங்கள்.',explore:'இசையை கேளுங்கள்',sniper:'SNIPER MODE ON',aboutTitle:'பீட்டுக்காக உருவாக்கப்பட்டது.',aboutText:'DJ Sniper என்பது high-energy DJ experiences, original music, collaborations மற்றும் digital content-ஐ மையமாகக் கொண்ட music & entertainment brand.',card1:'இசை',card1t:'DJ sets, mixes, rap, kuthu மற்றும் original sounds.',card2:'எனர்ஜி',card2t:'Powerful sound, attitude மற்றும் unforgettable moments.',card3:'Collabs',card3t:'Artists, creators, events மற்றும் brands உடன் collaboration.',musicTitle:'இசை வித்தியாசமாக இருக்கும்.',videoTitle:'வீடியோக்கள் & உள்ளடக்கம்',ytLater:'YouTube channel விரைவில்.',servicesTitle:'சத்தமாக ஏதாவது உருவாக்கலாம்.',service1:'DJ Booking',service1t:'Events, parties மற்றும் special occasions.',service2:'Music Projects',service2t:'Rap, DJ, kuthu மற்றும் creative music projects.',service3:'Events & Collabs',service3t:'Artists, event teams, creators மற்றும் brands.',contactTitle:'Booking • Collaboration • தொடர்பு',youtubeLater:'YouTube: விரைவில்'},
  gu:{navHome:'મુખ્ય પૃષ્ઠ',navAbout:'અમારા વિશે',navMusic:'સંગીત',navVideos:'વિડિઓ',navServices:'સેવાઓ',navContact:'સંપર્ક',eyebrow:'DJ • સંગીત • મનોરંજન',tagline:'સંગીતનો અંદાજ અલગ છે.',heroText:'એનર્જી વધારો. બીટ અનુભવો. Sniper Mode માં આવો.',explore:'સંગીત સાંભળો',sniper:'SNIPER MODE ON',aboutTitle:'બીટ માટે તૈયાર.',aboutText:'DJ Sniper સંગીત અને મનોરંજન બ્રાન્ડ છે, જે DJ અનુભવ, original music, collaborations અને digital content પર કેન્દ્રિત છે.',card1:'સંગીત',card1t:'DJ sets, mixes, rap, kuthu અને original sounds.',card2:'એનર્જી',card2t:'Powerful sound, attitude અને યાદગાર ક્ષણો.',card3:'Collabs',card3t:'Artists, creators, events અને brands સાથે collaboration.',musicTitle:'સંગીતનો અંદાજ અલગ છે.',videoTitle:'વિડિઓ અને કન્ટેન્ટ',ytLater:'YouTube channel ટૂંક સમયમાં.',servicesTitle:'ચાલો કંઈક જોરદાર બનાવીએ.',service1:'DJ Booking',service1t:'Events, parties અને special occasions.',service2:'Music Projects',service2t:'Rap, DJ, kuthu અને creative music projects.',service3:'Events & Collabs',service3t:'Artists, event teams, creators અને brands.',contactTitle:'Booking • Collaboration • સંપર્ક',youtubeLater:'YouTube: ટૂંક સમયમાં'},
  bn:{navHome:'হোম',navAbout:'আমাদের সম্পর্কে',navMusic:'সঙ্গীত',navVideos:'ভিডিও',navServices:'পরিষেবা',navContact:'যোগাযোগ',eyebrow:'DJ • সঙ্গীত • বিনোদন',tagline:'সঙ্গীতের অনুভূতি আলাদা।',heroText:'এনার্জি বাড়ান। বিট অনুভব করুন। Sniper Mode-এ আসুন।',explore:'সঙ্গীত শুনুন',sniper:'SNIPER MODE ON',aboutTitle:'বিটের জন্য তৈরি।',aboutText:'DJ Sniper একটি music ও entertainment brand, যা high-energy DJ experiences, original music, collaborations এবং digital content নিয়ে কাজ করে।',card1:'সঙ্গীত',card1t:'DJ sets, mixes, rap, kuthu এবং original sounds.',card2:'এনার্জি',card2t:'Powerful sound, attitude এবং unforgettable moments.',card3:'Collabs',card3t:'Artists, creators, events এবং brands-এর সঙ্গে collaboration.',musicTitle:'সঙ্গীতের অনুভূতি আলাদা।',videoTitle:'ভিডিও ও কনটেন্ট',ytLater:'YouTube channel শীঘ্রই আসছে।',servicesTitle:'চলুন কিছু জোরালো তৈরি করি।',service1:'DJ Booking',service1t:'Events, parties এবং special occasions.',service2:'Music Projects',service2t:'Rap, DJ, kuthu এবং creative music projects.',service3:'Events & Collabs',service3t:'Artists, event teams, creators এবং brands.',contactTitle:'Booking • Collaboration • যোগাযোগ',youtubeLater:'YouTube: শীঘ্রই'},
  te:{navHome:'హోమ్',navAbout:'మా గురించి',navMusic:'సంగీతం',navVideos:'వీడియోలు',navServices:'సేవలు',navContact:'సంప్రదింపు',eyebrow:'DJ • సంగీతం • వినోదం',tagline:'సంగీతం ప్రత్యేకంగా ఉంటుంది.',heroText:'ఎనర్జీ పెంచండి. బీట్‌ను అనుభవించండి. Sniper Mode‌లోకి రండి.',explore:'సంగీతం వినండి',sniper:'SNIPER MODE ON',aboutTitle:'బీట్ కోసం సిద్ధం.',aboutText:'DJ Sniper అనేది high-energy DJ experiences, original music, collaborations మరియు digital content పై దృష్టి పెట్టిన music & entertainment brand.',card1:'సంగీతం',card1t:'DJ sets, mixes, rap, kuthu మరియు original sounds.',card2:'ఎనర్జీ',card2t:'Powerful sound, attitude మరియు unforgettable moments.',card3:'Collabs',card3t:'Artists, creators, events మరియు brands తో collaboration.',musicTitle:'సంగీతం ప్రత్యేకంగా ఉంటుంది.',videoTitle:'వీడియోలు & కంటెంట్',ytLater:'YouTube channel త్వరలో.',servicesTitle:'ఏదైనా గట్టిగా క్రియేట్ చేద్దాం.',service1:'DJ Booking',service1t:'Events, parties మరియు special occasions.',service2:'Music Projects',service2t:'Rap, DJ, kuthu మరియు creative music projects.',service3:'Events & Collabs',service3t:'Artists, event teams, creators మరియు brands.',contactTitle:'Booking • Collaboration • సంప్రదింపు',youtubeLater:'YouTube: త్వరలో'},
  kn:{navHome:'ಮುಖಪುಟ',navAbout:'ನಮ್ಮ ಬಗ್ಗೆ',navMusic:'ಸಂಗೀತ',navVideos:'ವೀಡಿಯೊಗಳು',navServices:'ಸೇವೆಗಳು',navContact:'ಸಂಪರ್ಕ',eyebrow:'DJ • ಸಂಗೀತ • ಮನರಂಜನೆ',tagline:'ಸಂಗೀತದ ಅನುಭವ ವಿಭಿನ್ನ.',heroText:'ಎನರ್ಜಿ ಹೆಚ್ಚಿಸಿ. ಬೀಟ್ ಅನುಭವಿಸಿ. Sniper Mode ಗೆ ಬನ್ನಿ.',explore:'ಸಂಗೀತ ಕೇಳಿ',sniper:'SNIPER MODE ON',aboutTitle:'ಬೀಟ್‌ಗಾಗಿ ಸಿದ್ಧ.',aboutText:'DJ Sniper ಒಂದು music ಮತ್ತು entertainment brand ಆಗಿದ್ದು, high-energy DJ experiences, original music, collaborations ಮತ್ತು digital content ಮೇಲೆ ಗಮನಹರಿಸುತ್ತದೆ.',card1:'ಸಂಗೀತ',card1t:'DJ sets, mixes, rap, kuthu ಮತ್ತು original sounds.',card2:'ಎನರ್ಜಿ',card2t:'Powerful sound, attitude ಮತ್ತು unforgettable moments.',card3:'Collabs',card3t:'Artists, creators, events ಮತ್ತು brands ಜೊತೆ collaboration.',musicTitle:'ಸಂಗೀತದ ಅನುಭವ ವಿಭಿನ್ನ.',videoTitle:'ವೀಡಿಯೊಗಳು & ಕಂಟೆಂಟ್',ytLater:'YouTube channel ಶೀಘ್ರದಲ್ಲೇ.',servicesTitle:'ಬನ್ನಿ, ಜೋರಾದದ್ದನ್ನು ಸೃಷ್ಟಿಸೋಣ.',service1:'DJ Booking',service1t:'Events, parties ಮತ್ತು special occasions.',service2:'Music Projects',service2t:'Rap, DJ, kuthu ಮತ್ತು creative music projects.',service3:'Events & Collabs',service3t:'Artists, event teams, creators ಮತ್ತು brands.',contactTitle:'Booking • Collaboration • ಸಂಪರ್ಕ',youtubeLater:'YouTube: ಶೀಘ್ರದಲ್ಲೇ'},
  ml:{navHome:'ഹോം',navAbout:'ഞങ്ങളെക്കുറിച്ച്',navMusic:'സംഗീതം',navVideos:'വീഡിയോകൾ',navServices:'സേവനങ്ങൾ',navContact:'ബന്ധപ്പെടുക',eyebrow:'DJ • സംഗീതം • വിനോദം',tagline:'സംഗീതം വ്യത്യസ്തമായി അനുഭവപ്പെടുന്നു.',heroText:'എനർജി ഉയർത്തൂ. ബീറ്റ് അനുഭവിക്കൂ. Sniper Mode-ലേക്ക് വരൂ.',explore:'സംഗീതം കേൾക്കൂ',sniper:'SNIPER MODE ON',aboutTitle:'ബീറ്റിനായി തയ്യാറായത്.',aboutText:'DJ Sniper high-energy DJ experiences, original music, collaborations, digital content എന്നിവയിൽ ശ്രദ്ധ കേന്ദ്രീകരിക്കുന്ന music & entertainment brand ആണ്.',card1:'സംഗീതം',card1t:'DJ sets, mixes, rap, kuthu, original sounds.',card2:'എനർജി',card2t:'Powerful sound, attitude, unforgettable moments.',card3:'Collabs',card3t:'Artists, creators, events, brands എന്നിവരുമായി collaboration.',musicTitle:'സംഗീതം വ്യത്യസ്തമായി അനുഭവപ്പെടുന്നു.',videoTitle:'വീഡിയോകളും കണ്ടന്റും',ytLater:'YouTube channel ഉടൻ.',servicesTitle:'നമുക്ക് ശക്തമായ ഒന്നുണ്ടാക്കാം.',service1:'DJ Booking',service1t:'Events, parties, special occasions.',service2:'Music Projects',service2t:'Rap, DJ, kuthu, creative music projects.',service3:'Events & Collabs',service3t:'Artists, event teams, creators, brands.',contactTitle:'Booking • Collaboration • ബന്ധപ്പെടുക',youtubeLater:'YouTube: ഉടൻ'},
  pa:{navHome:'ਮੁੱਖ ਪੰਨਾ',navAbout:'ਸਾਡੇ ਬਾਰੇ',navMusic:'ਸੰਗੀਤ',navVideos:'ਵੀਡੀਓ',navServices:'ਸੇਵਾਵਾਂ',navContact:'ਸੰਪਰਕ',eyebrow:'DJ • ਸੰਗੀਤ • ਮਨੋਰੰਜਨ',tagline:'ਸੰਗੀਤ ਦਾ ਅੰਦਾਜ਼ ਵੱਖਰਾ ਹੈ।',heroText:'ਐਨਰਜੀ ਵਧਾਓ। ਬੀਟ ਮਹਿਸੂਸ ਕਰੋ। Sniper Mode ਵਿੱਚ ਆਓ।',explore:'ਸੰਗੀਤ ਸੁਣੋ',sniper:'SNIPER MODE ON',aboutTitle:'ਬੀਟ ਲਈ ਤਿਆਰ।',aboutText:'DJ Sniper ਇੱਕ music ਅਤੇ entertainment brand ਹੈ ਜੋ high-energy DJ experiences, original music, collaborations ਅਤੇ digital content ਉੱਤੇ ਕੇਂਦਰਿਤ ਹੈ।',card1:'ਸੰਗੀਤ',card1t:'DJ sets, mixes, rap, kuthu ਅਤੇ original sounds.',card2:'ਐਨਰਜੀ',card2t:'Powerful sound, attitude ਅਤੇ unforgettable moments.',card3:'Collabs',card3t:'Artists, creators, events ਅਤੇ brands ਨਾਲ collaboration.',musicTitle:'ਸੰਗੀਤ ਦਾ ਅੰਦਾਜ਼ ਵੱਖਰਾ ਹੈ।',videoTitle:'ਵੀਡੀਓ ਅਤੇ ਕੰਟੈਂਟ',ytLater:'YouTube channel ਜਲਦੀ ਆ ਰਿਹਾ ਹੈ।',servicesTitle:'ਆਓ ਕੁਝ ਜ਼ਬਰਦਸਤ ਬਣਾਈਏ।',service1:'DJ Booking',service1t:'Events, parties ਅਤੇ special occasions.',service2:'Music Projects',service2t:'Rap, DJ, kuthu ਅਤੇ creative music projects.',service3:'Events & Collabs',service3t:'Artists, event teams, creators ਅਤੇ brands.',contactTitle:'Booking • Collaboration • ਸੰਪਰਕ',youtubeLater:'YouTube: ਜਲਦੀ'},
  sa:{navHome:'मुखपृष्ठम्',navAbout:'अस्माकं विषये',navMusic:'सङ्गीतम्',navVideos:'दृश्यचित्राणि',navServices:'सेवाः',navContact:'सम्पर्कः',eyebrow:'DJ • सङ्गीतम् • मनोरञ्जनम्',tagline:'सङ्गीतस्य अनुभूतिः विशिष्टा अस्ति।',heroText:'ऊर्जां वर्धयतु। तालं अनुभवन्तु। Sniper Mode मध्ये आगच्छतु।',explore:'सङ्गीतं शृणुत',sniper:'SNIPER MODE ON',aboutTitle:'तालाय सज्जम्।',aboutText:'DJ Sniper उच्च-ऊर्जा DJ अनुभव, मौलिक सङ्गीत, collaborations तथा digital content इत्येषु केन्द्रितः music & entertainment brand अस्ति।',card1:'सङ्गीतम्',card1t:'DJ sets, mixes, rap, kuthu तथा original sounds.',card2:'ऊर्जा',card2t:'Powerful sound, attitude तथा unforgettable moments.',card3:'Collabs',card3t:'Artists, creators, events तथा brands सह collaboration.',musicTitle:'सङ्गीतस्य अनुभूतिः विशिष्टा अस्ति।',videoTitle:'दृश्यचित्राणि एवं सामग्री',ytLater:'YouTube channel शीघ्रम् आगमिष्यति।',servicesTitle:'आगच्छन्तु, किञ्चित् प्रभावशालि निर्मामः।',service1:'DJ Booking',service1t:'Events, parties तथा special occasions.',service2:'Music Projects',service2t:'Rap, DJ, kuthu तथा creative music projects.',service3:'Events & Collabs',service3t:'Artists, event teams, creators तथा brands सह.',contactTitle:'Booking • Collaboration • सम्पर्कः',youtubeLater:'YouTube: शीघ्रम्'}
};

const lang = document.getElementById('language');
function applyLang(l){
  const d=T[l]||T.en;
  document.documentElement.lang=l;
  document.querySelectorAll('[data-i18n]').forEach(el=>{
    const key=el.dataset.i18n;
    if(d[key]) el.textContent=d[key];
  });
  try{localStorage.setItem('djSniperLanguage',l)}catch(e){}
}

if(lang){
  let saved='en';
  try{saved=localStorage.getItem('djSniperLanguage')||'en'}catch(e){}
  lang.value=T[saved]?saved:'en';
  applyLang(lang.value);
  lang.addEventListener('change',e=>applyLang(e.target.value));
}
